### ISSUE TITLE
Fail to execute mvnw spring-boot:run

### ISSUE THREAD

**Issue by hydra-yl** [k8spatterns/random-generator#1]
The error messages is:

`[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/XX/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
`

**Comment by rhuss** [comment]
Good find ! 

The README hasn't been updated as we in the course also to offer an alternative based on Quarkus.
Could you please run `mvnw` from within the `spring/` directory ?

**Comment by rhuss** [comment]
Sorry, just call

```
./mvnw -pl spring spring-boot:run
```

from the main directory. I updated the README accordingly. 

Thanks for reporting this !

**Comment by hydra-yl** [comment]
> `

Thanks, it works. BTW, there is an extra ` at the end of command line.

**Comment by rhuss** [comment]
Thanks for the feedback !
